# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
